name: Github Actions Example

on: 
  push:
    branches:
      master

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World"
      - run: ./giftcardreader 1 part2/crash1.gft
      - run: ./giftcardreader 1 part2/crash2.gft
      - run: ./giftcardreader 1 part2/hang1.gft
